Repository bitcoindevkit/rust-esplora-client, pull requests merged in 2024-09, with the labels that each got.

#96 fix(ci): code coverage `actions/upload-artifact` version
  .github/workflows/code_coverage.yml
  .github/workflows/cont_integration.yml
  README.md
Labels: ci

#93 refactor(async): refactoring async client and minor documentation improvements
  Cargo.toml
  src/api.rs
  src/async.rs
  src/blocking.rs
  src/lib.rs
Labels: documentation

#100 fix(blocking): `get_with_retry` is private method
  src/blocking.rs
Labels: documentation, enhancement
